<?php
$hash_fields = array();
$options['url_retorno'] = $options['url_retorno'] ? :
        ($this->config["return_to"] ? : null);
if ($options['url_retorno']) {
#URL completa para onde seu cliente será direcionado depois da finalização do pedido no Pagamento Digital.
    $hash_fields = $hash_fields + array(
        "url_retorno" => $options['url_retorno'],
        "redirect" => 'true',
        "redirect_time" => $options['redirect_time'] ? : ( $this->config["redirect_time"])
    );
};


$options['url_aviso'] = $options['url_aviso'] ? : ( $this->config["url_aviso"]);
$options['url_aviso'] = $options['url_aviso'] ? : $options['url_retorno'];
if ($options['url_aviso'])
    $hash_fields = $hash_fields + array("url_aviso" => $options['url_aviso']);


$hash_fields = $hash_fields + array(
#"encoding" => 'UTF-8',
    'email_loja' => $options['email'] ? : ( $this->config["email"]),
    'tipo_integracao' => 'PAD',
    'id_pedido' => $order->id,
    'frete' => $order->frete
);


foreach ($order->getProducts() as $i => $product) {
    $i+=1;
    $hash_fields = $hash_fields + array(
        "produto_qtde_{$i}" => $product['qtde'],
        "produto_codigo_{$i}" => $product['id'],
        "produto_descricao_{$i}" => $product['descricao'],
        "produto_valor_{$i}" => $product['preco'],
    );
}
$hash_fields += (array) $order->getExtrasMapped();


$to_gen_md5 = $hash_fields;
ksort($to_gen_md5);
array_walk($to_gen_md5, function(&$v, $k) {
            $v = urlencode($v);
            $v = "{$k}=$v";
        });
$to_gen_md5 = join('&', $to_gen_md5);
$hash_fields['hash'] = md5($to_gen_md5);

$url = $this->config['developer'] ? $this->url(array(),array('name' => 'pagamento_digital/development')) : \PagamentoDigital\Base::GATEWAY_URL;
?>

<form action="<?php echo $url; ?>" method='post' >
    <span style="display :none">
        <?php
        array_walk($hash_fields, function(&$v, $k) {
                    $v = strtr($v, "'", "\\'");
                    $v = "
                            <label>
                            <input name='{$k}' value='{$v}' type='text'/>
                            {$k}
                            </label>
                            ";
                });

        echo join('<br/>', $hash_fields);
        ?>
    </span>
    <button type="submit">Enviar</button>
</form>